; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Kide"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "KMK virtual"
#define MyAppURL "https://kmk-virtual.netlify.app/1.0.0"
#define MyAppExeName "Kide.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4D01B952-173F-443E-AA9F-864A053F3033}}
AppName=Kide
AppVersion=1.0
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher=KMK virtual
AppPublisherURL=https://kmk-virtual.netlify.app/1.0.0/
AppSupportURL=https://kmk-virtual.netlify.app/1.0.0/
AppUpdatesURL=https://kmk-virtual.netlify.app/1.0.0/
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\user\vscode\python\Kood\iss\License.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\user\vscode\python\Kood\dist
OutputBaseFilename=Kide-installer
SetupIconFile=C:\Users\user\vscode\python\Kood\iss\icon.ico
SolidCompression=yes
WizardStyle=modern
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\user\vscode\python\Kood\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Create a unique class for Kide to hold the right-click menu
Root: HKCU; Subkey: "Software\Classes\Kide.app"; ValueType: string; ValueName: ""; ValueData: "Kide Editor"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Kide.app\shell\UninstallKide"; ValueType: string; ValueName: ""; ValueData: "Uninstall Kide"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Kide.app\shell\UninstallKide\command"; ValueType: string; ValueName: ""; ValueData: """{uninstallexe}"""; Flags: uninsdeletekey

Root: HKCU; Subkey: "Software\Classes\Applications\Kide.exe"; ValueType: string; ValueName: "ProgID"; ValueData: "Kide.app"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\Applications\Kide.exe"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "Kide Editor"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\Kide.exe"; ValueType: string; ValueName: ""; ValueData: "{app}\Kide.exe"; Flags: uninsdeletevalue



[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

; [Run]
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

