; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Kood"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "KMK virtual"
#define MyAppURL "https://kmk-virtual.netlify.app/1.0.0"
#define MyAppExeName "kood.exe"
#define MyAppAssocName "Kood file"
#define MyAppAssocExt ".kd"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8B84A657-8875-4BA4-8BEA-8A75837CD94C}}
AppName=Kood
AppVersion=1.0
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher=KMK virtual
AppPublisherURL=https://kmk-virtual.netlify.app/1.0.0/
AppSupportURL=https://kmk-virtual.netlify.app/1.0.0/
AppUpdatesURL=https://kmk-virtual.netlify.app/1.0.0/
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\user\vscode\python\Kood\iss\License.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\user\vscode\python\Kood\dist
OutputBaseFilename=kood-installer
SetupIconFile=C:\Users\user\vscode\python\Kood\iss\icon.ico
SolidCompression=yes
WizardStyle=modern
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\user\vscode\python\Kood\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  { We use HKEY_CURRENT_USER because PrivilegesRequired is 'lowest' }
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;

  { Look for the path inside the existing Path string }
  Result := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';') = 0;
end;


procedure CurUninstallStepChanged(UninstallStep: TUninstallStep);
var
  Path: string;
  OldPath: string;
  AppDir: string;
begin
  if UninstallStep = usUninstall then
  begin
    AppDir := ExpandConstant('{app}');
    
    // Read the User Path
    if RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', Path) then
    begin
      OldPath := Path;
      
      // Remove the app directory and any double semicolons created by the removal
      StringChangeEx(Path, ';' + AppDir + ';', ';', True);
      StringChangeEx(Path, AppDir + ';', '', True);
      StringChangeEx(Path, ';' + AppDir, '', True);
      
      // Only write back if the path actually changed
      if Path <> OldPath then
      begin
        RegWriteExpandStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', Path);
      end;
    end;
  end;
end;

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
;Registry data from file kood.reg
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\kood.exe"; Flags: uninsdeletekey; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\kood.exe"; ValueType: string; ValueName: ""; ValueData: "C:\Users\%USERNAME%\AppData\Local\Programs\kood\kood.exe"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\kood.exe"; ValueType: string; ValueName: "Path"; ValueData: "C:\Users\%USERNAME%\AppData\Local\Programs\kood\"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
;End of registry data from file kood.reg
Root: HKA; Subkey: "Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; \
    Check: NeedsAddPath(ExpandConstant('{app}'))



; Add "Uninstall Kood" to the right-click menu of .exe files for this user
Root: HKCU; Subkey: "Software\Classes\exefile\shell\UninstallKood"; ValueType: string; ValueName: ""; ValueData: "Uninstall Kood"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\exefile\shell\UninstallKood\command"; ValueType: string; ValueName: ""; ValueData: """{uninstallexe}"""; Flags: uninsdeletekey

; Set the icon for .kd files
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\icon.ico"; Flags: uninsdeletevalue



[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

; [Run]
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

